config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :planets, only: [:index, :show, :new, :create]
  resources :spaceships, only: [:index, :show]
  resources :bookings, except: :destroy
  delete "bookings/:id", to: "bookings#destroy", as: "destroy_booking"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :planet
  belongs_to :spaceship

  validates :user, presence: true
  validates :spaceship, presence: true
  validates :planet, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  def sender?(this_user)
    user.id == this_user.id
  end
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  validates :distance, presence: true
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :manufacturer, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  def index
    # @bookings = Booking.where(user: current_user)
    if params[:query].present?
      sql_query = "planets.name ILIKE :query OR spaceships.name ILIKE :query"
      @bookings = policy_scope(Booking).joins(:planet).joins(:spaceship).where(sql_query, query: "%#{params[:query]}%")
    else
      @bookings = policy_scope(Booking)
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'bookings/searchlist', formats: :html, locals: { bookings: @bookings } }
    end
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    @spaceships = Spaceship.all
    @planets = Planet.all
    authorize @booking
  end

  def create
    @booking = Booking.create(
      user: current_user,
      spaceship: Spaceship.find(booking_params[:spaceship]),
      planet: Planet.find(booking_params[:planet])
    )
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      # flash[:error] = "Unable to create new booking."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @booking
    @spaceships = Spaceship.all
    @planets = Planet.all
  end

  def update
    authorize @booking
    @booking.update(
      user: current_user,
      spaceship: Spaceship.find(booking_params[:spaceship]),
      planet: Planet.find(booking_params[:planet])
    )
    if @booking.save
      redirect_to booking_path(@booking)
    else
      # flash[:error] = "Unable to update booking."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:spaceship, :planet, :user)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    authorize @chatroom
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find(params[:id])
  end

  def new
    @planet = Planet.new
  end

  def create
    @planet = Planet.create(planet_params)
    if @planet.save
      redirect_to planets_path
    else
      flash[:error] = "Unable to create new planet"
    end
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :distance, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_searchlist.html.erb
<div data-search-bookings-target="results">
  <ul>
    <% bookings.each do |booking| %>
      <li>
        <%= link_to "Trip to #{booking.planet.name} onboard the #{booking.spaceship.name}", booking_path(booking) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/bookings/edit.html.erb
<h1>Update booking to <%= "#{@booking.planet.name} on #{@booking.spaceship.name}" %></h1>
<%= simple_form_for @booking do |b| %>
  <%= b.input :spaceship, collection: @spaceships, selected: @booking.spaceship.id %>
  <%= b.input :planet, collection: @planets, selected: @booking.planet.id %>
  <%= b.submit %>
<% end %>

app/views/bookings/index.html.erb
<h1>All bookings</h1>
<div data-controller="search-bookings">
  <%= form_with url: bookings_path, method: :get,
    data: {
      search_bookings_target: "form",
      # action: "submit->search-bookings#send"
    } do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Find a booking",
      data: {
        search_bookings_target: "searchInput",
        action: "keyup->search-bookings#update"
      } %>
  <% end %>
  <%= render 'searchlist', bookings: @bookings %>
</div>

app/views/bookings/new.html.erb
<h1>Book your trip</h1>
<%= simple_form_for @booking do |b| %>
  <%= b.input :spaceship, collection: @spaceships %>
  <%= b.input :planet, collection: @planets %>
  <%= b.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1><%= "Your trip to #{@booking.planet.name} onboard #{@booking.spaceship.name}"%></h1>
<% if policy(@booking).edit? %>
  <%= link_to "Update your trip", edit_booking_path(@booking) %>
<% end %>
<% if policy(@booking).destroy? %>
  <%= link_to "Cancel this trip",
    destroy_booking_path(@booking),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
<% end %>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>"
>
  <h1>#<%= @chatroom.name %></h1>

  <div class="messages"
    data-chatroom-subscription-target="messages"
  >
    <% @chatroom.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>
  <%= simple_form_for [@chatroom, @message],
    html: {
      data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
      class: "d-flex"
    } do |f| %>
    <%= f.input :content,
      label: false,
      placeholder: "Message ##{@chatroom.name}",
      wrapper_html: { class: "flex-grow-1" }
    %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacebnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.first_name %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<h1>My Dashboard</h1>
<%= link_to "See planets to fly to", planets_path %>
<%= link_to "See all bookings", bookings_path %>

app/views/planets/index.html.erb
<h1>Book a trip to space!</h1>
<ul>
  <% @planets.each do |planet| %>
    <li>
      <%= cl_image_tag planet.photos.first.key, height: 50, width: 50 if planet.photos.first %>
      <%= link_to "#{planet.name}", planet_path(planet) %>
    </li>
  <% end %>
</ul>
<%= link_to "List a new planet to visit", new_planet_path %>

app/views/planets/new.html.erb
<h1>Create new planet listing</h1>
<%= simple_form_for(@planet) do |p| %>
  <%= p.input :name %>
  <%= p.input :distance, hint: "enter the distance in km" %>
  <%= p.input :photos, as: :file, input_html: {multiple: true} %>
  <%= p.submit %>
<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>
<% @planet.photos.each do |photo| %>
  <%= cl_image_tag photo.key %>
<% end %>
<%= link_to "Back to planet index", planets_path %>
<%= link_to "Book a trip to visit", new_booking_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top"
  data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar"
  data-navbar-target="navbar"
>
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://www.seekpng.com/png/detail/819-8191232_spaceship-black-clipart-space-ship-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item" data-action="click->navbar#toggleNavbarColor">
            <%= link_to "Change Navbar-Color", "#", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <a><%= current_user.first_name %></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New booking", new_booking_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>